name: Build & Deploy User Page

on:
  push:
    branches:
      - gh-pages   # your source branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Pull down your code from gh-pages
      - name: Checkout source (gh-pages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -rf ./*
          git clone --depth=1 \
            --branch gh-pages \
            https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} \
            .

      # 2. Install Node v14.17.3
      - name: Install Node.js v14.17.3 locally
        run: |
          curl -fsSLO https://nodejs.org/dist/v14.17.3/node-v14.17.3-linux-x64.tar.xz
          tar -xf node-v14.17.3-linux-x64.tar.xz
          mv node-v14.17.3-linux-x64 node
          echo "$PWD/node/bin" >> $GITHUB_PATH

      # 3. Build your Vue app
      - name: npm ci & build
        run: |
          npm ci
          npm run build

      # 4. Push the static output to master
      - name: Deploy to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          # clone master into 'site'
          git clone --depth=1 --branch master \
            https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} site
          rm -rf site/*           # wipe old files
          cp -r dist/* site/      # copy new build
          cd site
          git add --all
          # only commit if there are changes
          git diff-index --quiet HEAD || git commit -m "Deploy from gh-pages (${{ github.sha }})"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:master --force
