name: Build & Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: use Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: '14.17.3'   # ← your exact version

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
