name: Build & Deploy to master

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your source from main
      - name: Checkout source
        run: |
          rm -rf ./*
          git clone --depth=1 \
            --branch main \
            https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ./

      # 2) Install Node.js v14.17.3 locally
      - name: Install Node.js v14.17.3
        run: |
          curl -fsSLO https://nodejs.org/dist/v14.17.3/node-v14.17.3-linux-x64.tar.xz
          tar -xf node-v14.17.3-linux-x64.tar.xz
          mv node-v14.17.3-linux-x64 node
          echo "$PWD/node/bin" >> $GITHUB_PATH

      # 3) Build your Vue app
      - name: npm ci & build
        run: |
          npm ci
          npm run build

      # 4) Deploy the compiled dist/ to master
      - name: Deploy to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # → ensure git can commit
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          # → clone master into `site/` (or init if it doesn’t exist)
          rm -rf site
          git clone --depth=1 \
            --branch master \
            https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} site || \
          ( git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} site && cd site && git checkout --orphan master )

          # → replace everything with your fresh build
          rm -rf site/*
          cp -r dist/* site/

          # → commit & force-push back to master
          cd site
          git add --all
          git commit -m "Deploy from main @ ${{ github.sha }}" --allow-empty
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:master --force
