name: Build & Deploy User Page

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source (main)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Use Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install & build
        run: |
          npm ci
          npm run build

      - name: Deploy to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          # clone master into site
          git clone --depth=1 --branch master \
            https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} site
          rm -rf site/*
          cp -r .next/static site/_next/static
          cp -r out/* site/         # assuming you used `next export` into `out/`
          cd site
          git add --all
          git diff-index --quiet HEAD || git commit -m "Deploy from main @ ${{ github.sha }}"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:master --force
