name: Build & Deploy to gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your source-code on main
      - name: Checkout source
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -rf ./*
          git clone --depth=1 \
            --branch main \
            https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} ./

      # 2️⃣ Install Node.js v14.17.3 locally
      - name: Install Node.js v14.17.3
        run: |
          curl -fsSLO https://nodejs.org/dist/v14.17.3/node-v14.17.3-linux-x64.tar.xz
          tar -xf node-v14.17.3-linux-x64.tar.xz
          mv node-v14.17.3-linux-x64 node
          echo "$PWD/node/bin" >> $GITHUB_PATH

      # 3️⃣ Build your Vue app
      - name: npm ci & build
        run: |
          npm ci
          npm run build

      # 4️⃣ Deploy the compiled `dist/` to gh-pages
      - name: Deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          # clone an empty gh-pages branch (or existing one)
          rm -rf site
          git clone --depth=1 \
            --branch gh-pages \
            https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} site || \
          ( git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} site && cd site && git checkout --orphan gh-pages )

          # overwrite it with your dist/
          rm -rf site/*
          cp -r dist/* site/

          # commit & force-push
          cd site
          git add --all
          git commit -m "Deploy from ${{ github.sha }}" --allow-empty
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:gh-pages --force
